### ISSUE TITLE
The night splash screen is shown during the day

### ISSUE THREAD

**Issue by mstuyts** [NathanW2/qgis_hats#21]
The night splash screen is shown during the day, because the plugin uses yesterdays sun.json file and doesn't ignore the date.

in this case with QDateTime as '%d/%m/%Y %H:%M':
* now = 12/02/2019 13:31
* sunrise = 11/02/2019 06:59
* sunset = 11/02/2019 16:50

Since now is not between sunrise and sunset, the night splash screen is shown.

Only the time should be checked and the date should be ignored.

**Comment by mstuyts** [comment]
I created a pull request (#22) to solve this problem.

**Comment by NathanW2** [comment]
Thanks.  Finally got around to getting another release out. :)
