### ISSUE TITLE
Hat Ideas for December 25

### ISSUE THREAD

**Issue by hareldunn** [NathanW2/qgis_hats#3]
So have this idea for a hat for 12-25, what do you think? ;)
![qgis-icon-60x60_xmas](https://cloud.githubusercontent.com/assets/24369355/20890407/7201cbf4-bb0f-11e6-9849-1a018ea43c74.png)

**Comment by SteveLowman** [comment]
We are a little disturbed here that our Santa hat has been replaced by a top hat.
It is a very nice top hat, but we need the seasonal hat for December please.

**Comment by NathanW2** [comment]
Added xmas hat back for default for 12th month
